FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

EXPOSE 5000

ENV NAME World

# Run app.py when the container launches
CMD ["python", "backend.py", "--host", "0.0.0.0"]