FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
COPY app.py ./app.py
COPY config.ini ./config.ini
COPY model/decision_tree_model.joblib ./model/decision_tree_model.joblib

RUN pip install -r requirements.txt

EXPOSE 8501

# CMD ["streamlit", "run", "./app.py", "--browser.gatherUsageStats", "False"]
CMD ["streamlit", "run", "./app.py", "--server.port=8501", "--server.address=0.0.0.0"]
